### ISSUE TITLE
[request] Sign Copy + Invisible Frame

### ISSUE THREAD

**Issue by Anoaxx** [Ivan0xFF/ImprovedSigns#15]
Option to do this can be very helpful. 

Something like another keybind to copy signs and remove frames visibility. 

If you don't want to do this just close this issue. Love all your work. <3

**Comment by Ivan0xFF** [comment]
These are both great ideals. I'll look into it.

**Comment by Anoaxx** [comment]
invisible frames can be do like Left Shift + Left Click, but I don't know if this work well with Coping Signs

**Comment by Ivan0xFF** [comment]
Sign Copy has been merged, invisible frames are dependent on this PR https://github.com/Ivan0xFF/BetterSignsAndFrames/pull/22

Both should be in the next release

**Comment by LuciusofLegend** [comment]
There is also the Invis Frames mod which is licensed under MIT, meaning you could copy and paste their code.

**Comment by Ivan0xFF** [comment]
Merged
