### ISSUE TITLE
Chest sound duplucated while opening a chest through an itemframe

### ISSUE THREAD

**Issue by John-Development** [Ivan0xFF/ImprovedSigns#18]
Im playing the latest release of the mod in 1.18.2 with fabric, using both client side and server side (playing in a server). Seems like when I want to open a chest, the sound of it opening is duplicated if I do it through an itemframe (even if it is empty), but sounds only once if I open the same chest from an empty side.

This does not appear to happen with signs.

**Comment by Ivan0xFF** [comment]
Fixed by dae9f7256848a71d74187283472495f6e0eae3a5
