### ISSUE TITLE
Placing Amethyst Shards/Glass Panes in an item frame is impossible without turning the frame invisible

### ISSUE THREAD

**Issue by Ivan0xFF** [Ivan0xFF/ImprovedSigns#24]
I'm open to ideas for how we could allow people to still have shards/panes in item frames with the current invisible frame functionality.

**Comment by Ivan0xFF** [comment]
I think the simple solution is not turn frames invisible if they don't have any items in them. So you could then click on a sign with an Amethyst, placing an Amethyst in it, then click on it again turning it invisible.

**Comment by kingstairs** [comment]
That is a reasonable workaround for the issue. Another option is to _craft_ "invisible frames" (normal frame + amethyst/glass) before placement (if that makes sense?) - I'm assuming that the current process is changing the item frame into a new item.

**Comment by Ivan0xFF** [comment]
The problem with crafting them is that they'd be very easy to lose. Someone could craft 100 invisible frames, cover your base in them and you'd be wondering why you can't place items.

Nice thing about not being able to turn frames invisible if they're not filled is that it also gets around that issue.

**Comment by kingstairs** [comment]
Yes, I can see someone doing that... ;-)
One solution to that mischief: Treat empty frames just like normal item frames (i.e., display them) that turn invisible when something is actually displayed. I think this is the approach some of the other frame mods use (probably for the same reason you mentioned).

**Comment by Ivan0xFF** [comment]
Fixed by dae9f7256848a71d74187283472495f6e0eae3a5
